global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: 'app-a'
    scrape_interval: 5s
    scheme: https  # Changed to https
    tls_config:
      insecure_skip_verify: true  # Only if using self-signed certs
    static_configs:
      - targets: ['${REMOTE_APP_A}']
    metrics_path: /app-a/metrics

  - job_name: 'app-b'
    scrape_interval: 5s
    scheme: https  # Changed to https
    tls_config:
      insecure_skip_verify: true  # Only if using self-signed certs
    static_configs:
      - targets: ['${REMOTE_APP_B}']
    metrics_path: /app-b/metrics

  - job_name: 'app-c'
    scrape_interval: 5s
    scheme: https  # Changed to https
    tls_config:
      insecure_skip_verify: true  # Only if using self-signed certs
    static_configs:
      - targets: ['${REMOTE_APP_C}']
    metrics_path: /app-c/metrics
